### ISSUE TITLE
adapt a model

### ISSUE THREAD

**Issue by rahmirtrt** [Teriks/dgenerate#4]
How can I adapt a model from spandrel to dgenerate? Which lines, which files should I delete and add? Can you tell me or help me?

for example:
How do I add this model to dgenerate?
https://github.com/chaiNNer-org/spandrel/tree/main/libs/spandrel/spandrel/architectures/SAFMNBCIE

**Comment by Teriks** [comment]
If they have not made a release with this architecture present, you can try installing spandrel directly from their main branch into the environment that dgenerate is using, this might work if you have installed dgenerate manually into a virtual environment.  It will not work for the windows installer.

You might need to install Git For Windows to use this pip feature

`pip install git+https://github.com/chaiNNer-org/spandrel`

**Comment by rahmirtrt** [comment]
I did pip install git+https://github.com/chaiNNer-org/spandrel

Then I manually moved the files from https://github.com/chaiNNer-org/ or C:\Program Files\Python311\Lib\site-packages\libs\spandrel spandrel to C:\Program Files\dgenerate345lite\_internal\spandrel folder. 
I could not run the SAFMNBCIE model in dgenerate.

**Comment by Teriks** [comment]
It will not work for the windows installer environment, for your usage I would suggest not using the installer and instead installing dgenerate into a virtual environment

for instance 

```
# create environment

python -m venv dgenerate_env

# activate environment, must be done every time before running dgenerate

dgenerate_env\Scripts\activate

pip install dgenerate --extra-index-url https://download.pytorch.org/whl/cu121/
pip install git+https://github.com/chaiNNer-org/spandrel

```

**Comment by rahmirtrt** [comment]
I could not get the newly added https://github.com/chaiNNer-org/spandrel/tree/main/libs/spandrel/spandrel/architectures/SAFMNBCIE model to work at all.
It is best to make a command or .bat file that will add and run the new auto detect model to the dgenerate.

**Comment by rahmirtrt** [comment]
spandrel updated. 0.3.2 version
